{{- if .Values.index.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Chart.Name "shared" }}
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
  {{- if .Values.index.annotations }}
  annotations:
  {{ toYaml .Values.index.annotations | indent 4 }}
  {{- end }}
data:
  PG_USERNAME: {{ .Values.config.shared.PG_USERNAME | b64enc }}
  PG_PASS: {{ .Values.config.shared.PG_PASS | b64enc }}
  PG_HOST: {{ .Values.config.shared.PG_HOST | b64enc }}
  PG_PORT: {{ .Values.config.shared.PG_PORT | b64enc }}
  PG_DB: {{ .Values.config.shared.PG_DB | b64enc }}
{{- end }}

---
{{- if .Values.index.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Chart.Name "tomlconfig" }}
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
    {{- include "hedera-the-graph-node.index.selectorLabels" . | nindent 4 }}
  {{- if .Values.index.annotations }}
  annotations:
  {{ toYaml .Values.index.annotations | indent 4 }}
  {{- end }}
data:
  config.toml: {{ include "hedera-the-graph-node.config" . | b64enc }}  
{{- end }}