{{- if .Values.index.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Chart.Name "shared" }}
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
  {{- if .Values.index.annotations }}
  annotations:
  {{ toYaml .Values.index.annotations | indent 4 }}
  {{- end }}
stringData:
  PG_USERNAME: {{ .Values.config.shared.PG_USERNAME }}
  PG_PASS: {{ .Values.config.shared.PG_PASS }}
  PG_HOST: {{ .Values.config.shared.PG_HOST }}
  PG_PORT: {{ .Values.config.shared.PG_PORT }}
  PG_DB: {{ .Values.config.shared.PG_DB }}
{{- end }}
