{{- if and .Values.index.enabled .Values.index.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Chart.Name "index" }}
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
  {{- if .Values.index.annotations }}
  annotations:
  {{ toYaml .Values.index.annotations | indent 4 }}
  {{- end }}
{{- end }}