{{- if and .Values.query.enabled .Values.query.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Chart.Name "query" }}
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
    app: {{ printf "%s-%s" .Chart.Name "query" }}
  {{- if .Values.index.annotations }}
  annotations:
  {{ toYaml .Values.index.annotations | indent 4 }}
  {{- end }}
{{- end }}